### ISSUE TITLE
This is an amazing image to pdf converter for windows which is not popular.

### ISSUE THREAD

**Issue by clicky6** [skinan/imap-Image-to-PDF-Converter-Application-For-Windows#2]
Sir this app is amazing, Thanks for making such an amazing app. There is no (open-source, free, offline) app available out there for windows or desktops which can convert image to pdf .I found this app and it has made converting image to pdf much much easier for me .But seeing such a wonderful app not gain much popularity is not a good thing. Adobe Acrobat DC which is only offline app for converting image to pdf is paid and is also proprietary and this is the very best alternative to it 
so Sir consider doing the following things to make this app rock and to reach more users.

Consider listing this app on https://alternativeto.net/ as an open-source, gui, good-looking image to pdf converter app for windows.
Listing it by this tag https://alternativeto.net/feature/image-to-pdf/?license=opensource&platform=windows
Listing it as an alternative to Adobe Acrobat DC and much more.
Such a wonderful app and is so underrated feels bad so Sir kindly do the following things to make this app reach users and so It can help many people.

**Comment by skinan** [comment]
Thank you so much for your appreciation. It really means a lot to us. And many thanks for your kind and great suggestions. We will surely follow your advice as soon as possible.
