### ISSUE TITLE
Please add this in app's features list.

### ISSUE THREAD

**Issue by clicky6** [skinan/imap-Image-to-PDF-Converter-Application-For-Windows#4]
Sir did you knew that your Image to PDF silently compresses pdf and makes the size of the PDF smaller.

PROOF 
I took 3 jpg pictures all of size 3 mb approx. and 3*3=9 mb
Then when the PDF was made I was shocked the PDF was only of 4 mb and it had no quality loss.

And this feature was not even listed in features list.

How was this thing done?

Best compressing I have ever seen in any pdf app.

**Comment by skinan** [comment]
Thank you for the appreciation!
